polkadot-js/common

lerna.json
package.json
packages/db/package.json
packages/trie-db/package.json
packages/trie-hash/package.json
packages/util-crypto/package.json
packages/util-keyring/package.json
packages/util-keyring/src/index.spec.js
packages/util-keyring/src/index.ts
packages/util-keyring/src/pairs.ts
packages/util-keyring/src/testing.ts
packages/util-keyring/src/types.d.ts
packages/util-rlp/package.json
packages/util/package.json
yarn.lock

Aligns and simplifies use of Keyring with the rest of the interfaces where closures have been converted to ES6 objects. (e.g. large parts of the API)
Going from 
```
import createKeyring from '@polkadot/util-keyring';
const keyring = createKeyring();
const pair = keyring.addFromSeed(<some_seed>);
const signature = pair.sign(<some_message>);
```
to new version -
```
import Keyring from '@polkadot/util-keyring';
const keyring = new Keyring();
const pair = keyring.addFromSeed(<some_seed>);
const signature = pair.sign(<some_message>);
```
There will be work on the UI side now as well to implement this is ui-keyring. (Probably inherit from object and add the new methods?)
cc @chevdor 
cc @ltfschoen

Classify Keyring

---

packages/util/src/is/hex.spec.js
packages/util/src/is/hex.ts
packages/util/src/is/string.spec.js
packages/util/src/is/string.ts

We'll have in the api `class Text extends String`. Instead of writing everywhere `if (isString(value) || value instanceof String)`, I prefer to factorize it here.

isString true for String object

---

packages/util-crypto/src/schnorrkel/schnorrkel-js/schnorrkel_js.js

Related to https://github.com/paritytech/schnorrkel-js/issues/7
```
Critical dependency: the request of a dependency is an expression
```

Really fix "dep as expression" (webpack)

---

packages/util-crypto/src/schnorrkel/schnorrkel-js/schnorrkel_js.js

Mentioned in https://github.com/paritytech/schnorrkel-js/issues/7

Error stub require, cleans up webpack warnings

---

packages/util/src/is/index.ts
packages/util/src/is/jsonObject.spec.ts
packages/util/src/is/jsonObject.ts

Checks to see if the input value is a valid JSON object.
It returns false if the input is JSON parsable, but not an Javascript object.
Use-cases:
- To validate if uploaded files contain valid JSON objects
- To validate if manual code input in editors contains valid JSON objects

Parsing function for JSON objects

---

packages/keyring/src/defaults.ts
packages/keyring/src/index.spec.ts
packages/keyring/src/index.ts
packages/keyring/src/testing.ts

Align with subkey, i.e. when `//Alice` is specified as an suri, auto-add the `<dev-phrase>` so the suri becomes `<dev-phrase>//Alice`
cc @drewstone

Shortcut for creating dev accounts

---

.gitignore
packages/db/src/FileFlatDb/Impl.ts
packages/db/src/FileFlatDb/Serialize.ts
packages/db/src/FileFlatDb/ViaTrie.spec.ts
packages/db/src/FileFlatDb/defaults.ts
packages/db/src/FileFlatDb/index.spec.ts
packages/db/src/FileFlatDb/types.ts

This makes a tradeof with slightly larger initial size (which should even out as more keys are added and the space gets filled), while allowing for faster writes and less reads.

Fix FileDb nibble length, use to 256-entry headers

---

packages/util/src/assertSingletonPackage.ts

Currently this happens -
```
$ ts-node cli.ts --help
/home/user/cw/edgeware-apps/node_modules/@polkadot/types/node_modules/@polkadot/util/assertSingletonPackage.js:23
const _global = (0, _undefined.default)(window) ? global : window;
^
ReferenceError: window is not defined
```

use typeof window (for global detection)

---

CHANGELOG.md
packages/util-crypto/package.json
packages/util-crypto/src/nacl/sign.ts
packages/util-crypto/src/nacl/verify.ts
packages/util-crypto/src/schnorrkel/sign.ts
packages/util-crypto/src/schnorrkel/verify.ts
yarn.lock

Would make sense to include the update from https://github.com/polkadot-js/wasm/pull/20 in here as well (non-functionality, but `w3f/schnorrkel` is bumped to 0.1.1 in there to align with substrate.
Based on feedback in actual use by @jnaviask

Allow string params for sr25519/ed25519 sign & verify

---

packages/trie-db/src/Impl.ts
packages/trie-db/src/index.ts
packages/trie-db/src/snapshot.spec.ts
packages/trie-db/src/types.ts

- optimize snapshot with one less encoding operation (retrieve raw & encoded, never decode and immediate re-encode)
- Add entries() to return Array<[root, encoded, ...childRoots]> - which can be used to re-construct
- Add getEntry(root?) to return [root, encoded, ...childRoots] - showing a root and all dependent roots

Add entries() method to trie

---

packages/util/src/format/formatBalance.spec.ts
packages/util/src/format/formatBalance.ts
packages/util/src/format/si.ts

when a number decimals is too high, const mid will be a negative.
```
it('formats 123,456,789,000 (decimals=36)', (): void => {
expect(
formatBalance(TESTVAL, true, 36)
).toEqual('0.123y Unit');
});
```

Handing high decimals scenes

---

package.json
packages/util/src/format/formatBalance.spec.ts
packages/util/src/format/formatBalance.ts
packages/util/src/format/si.ts
yarn.lock

This allows the formatting of a balance to a specific SI unit, instead of a calculated one. i.e. `formatBalance(123456, { forceUnit: '-' })` will format as `123,456.000`

Allow forcing of units in formatBalance

---

packages/util-crypto/src/address/ss58.ts

This adds Kulupu prefix 16 (mainnet) and 17 (reserved) to the list of `allowedSS58`.

ss58: add Kulupu prefix to the list

---

CHANGELOG.md
package.json
packages/util-crypto/src/key/DeriveJunction.ts
packages/util/src/types.ts
yarn.lock

Also closes https://github.com/polkadot-js/common/pull/504 by using `import type` to indicate actual usage.

Adjust DeriveJunction (types & BigInt)

---

CHANGELOG.md
lerna.json
package.json
packages/keyring/package.json
packages/keyring/src/index.spec.ts
packages/keyring/src/keyring.ts
packages/keyring/src/pair/decode.ts
packages/keyring/src/pair/defaults.ts
packages/keyring/src/pair/encode.spec.ts
packages/keyring/src/pair/encode.ts
packages/keyring/src/pair/index.ts
packages/keyring/src/pair/toJson.spec.ts
packages/keyring/src/pair/toJson.ts
packages/keyring/src/types.ts
packages/util-crypto/package.json
packages/util-crypto/src/index.ts
packages/util-crypto/src/pbkdf2/encode.ts
packages/util-crypto/src/pbkdf2/index.ts
packages/util-crypto/src/scrypt/defaults.ts
packages/util-crypto/src/scrypt/encode.ts
packages/util-crypto/src/scrypt/fromU8a.ts
packages/util-crypto/src/scrypt/index.ts
packages/util-crypto/src/scrypt/toU8a.ts
packages/util-crypto/src/scrypt/types.ts
packages/util/package.json
yarn.lock

Still TODO in follow-up PRs in the 3 series -
- WASM scrypt (https://docs.rs/scrypt/0.3.1/scrypt/), currently a bit problematic since the WASM build is still restructured and not quite stable with the upgrades to wasmpack
- https://github.com/polkadot-js/common/issues/638

Keyring JSON with kdf

---

packages/util-crypto/src/address/ss58.ts

Adding 4 as address type of ss58 for Katal Chain

Adding 4 as address type of ss58 for Katal Chain

---

packages/util-crypto/src/key/extractSuri.spec.ts
packages/util-crypto/src/key/extractSuri.ts

I ran into a case where the secret value provided had trailing
whitespace, and when the code ran, it logged that secret value as part
of the stack trace.
This change will make it harder for users to accidentally leak key
material.

[FIX] Adjust error message

---

packages/keyring/src/keyring.ts
packages/keyring/src/pair/index.ts
packages/util-crypto/src/ethereum/encode.ts
packages/util-crypto/src/key/fromPath.ts
packages/util-crypto/src/secp256k1/hasher.ts
packages/util-crypto/src/secp256k1/keypair/fromSeed.ts
packages/util-crypto/src/secp256k1/sign.ts
packages/util-crypto/src/secp256k1/signVerify.spec.ts
packages/util-crypto/src/secp256k1/verify.ts
packages/util-crypto/src/signature/verify.ts
packages/util-crypto/src/types.ts

Part of https://github.com/polkadot-js/common/issues/656
Sadly this is where things starts going off-the-rails -
- MultiSignature doesn't have a specific Ethereum byte (Potentially same as normal ecdsa?)
- Not sure about the publicKey hashing
- the actual generated pairs from the same seed is non-Ethereum compatible

Ethereum keypair support

---

packages/keyring/src/index.spec.ts
packages/keyring/src/keyring.ts
packages/keyring/src/pair/index.spec.ts
packages/keyring/src/pair/index.ts
packages/util-crypto/src/ethereum/encode.spec.ts
packages/util-crypto/src/ethereum/encode.ts
packages/util-crypto/src/mnemonic/index.ts
packages/util-crypto/src/mnemonic/toBip39.spec.ts
packages/util-crypto/src/mnemonic/toBip39.ts
packages/util-crypto/src/secp256k1/compress.spec.ts
packages/util-crypto/src/secp256k1/compress.ts
packages/util-crypto/src/secp256k1/expand.spec.ts
packages/util-crypto/src/secp256k1/expand.ts
packages/util-crypto/src/secp256k1/index.ts
packages/util-crypto/src/secp256k1/sanitizePublic.ts

Part of #656 
- Re-adds the Ethereum/Bitcoin compatible mnemonic -> seed conversions (dropped in https://github.com/polkadot-js/common/pull/606 since it was only used in the poc-1/poc-2 timeframe)
- Expands tests in pairs and keyring

Add Ethereum-compatible seed from mnemonic

---

packages/util-crypto/src/address/ss58.ts

Taking 21 and 22 for testnet and mainnet
Signed-off-by: lovesh <lovesh.bond@gmail.com>

Add Dock network id for address generation

---

packages/util-crypto/src/address/addressToEvm.spec.ts
packages/util-crypto/src/address/addressToEvm.ts
packages/util-crypto/src/address/evmToAddress.spec.ts
packages/util-crypto/src/address/evmToAddress.ts
packages/util-crypto/src/address/index.ts

Adds two utils for manipulating EVM addresses.
* addressToEvm is based on logic here: https://github.com/paritytech/substrate/blob/frontier/frame/evm/src/lib.rs#L148 and truncates a Substrate public key to a 20-byte Ethereum key.
* evmToAddress is based on logic here: https://github.com/paritytech/substrate/blob/frontier/frame/evm/src/lib.rs#L169 and hashes a 20-byte Ethereum key to produce a 32-byte Substrate public key.

Add evmToAddress and addressToEvm crypto utils.

---

packages/keyring/src/pair/index.ts
packages/util-crypto/src/secp256k1/verify.ts
packages/util-crypto/src/signature/verify.spec.ts

This PR will fix the verify function from crypto-util so that it can be used by the Verify component for ethereum addresses.
The problem was that the verify function expected a 36bytes address instead of the truncated 20bytes address used by ethereum.
I added two tests

Add eth tests and truncate address for keccak

---

packages/keyring/src/pair/index.ts
packages/util-crypto/src/secp256k1/sign.ts
packages/util-crypto/src/secp256k1/signVerify.spec.ts
packages/util-crypto/src/secp256k1/verify.spec.ts
packages/util-crypto/src/secp256k1/verify.ts
packages/util-crypto/src/signature/verify.spec.ts
packages/util-crypto/src/signature/verify.ts

Closes https://github.com/polkadot-js/common/issues/759
Always assumed that in keccak mode we are dealing with Ethereum addresses. Remove the expansion part (caller ensures address is correctly specified)

Cleanup/simplify ETH signing

---

packages/keyring/src/index.spec.ts
packages/keyring/src/pair/index.spec.ts
packages/networks/src/index.ts
packages/networks/src/types.ts
packages/util-crypto/src/address/check.ts
packages/util-crypto/src/address/checksum.spec.ts
packages/util-crypto/src/address/checksum.ts
packages/util-crypto/src/address/decode.spec.ts
packages/util-crypto/src/address/decode.ts
packages/util-crypto/src/address/defaults.ts
packages/util-crypto/src/address/encode.spec.ts
packages/util-crypto/src/address/encode.ts
packages/util-crypto/src/address/eq.spec.ts
packages/util-crypto/src/address/setSS58Format.spec.ts

To be checked against https://github.com/paritytech/substrate/pull/8039

Allow double-byte ss58

---

packages/keyring/src/index.spec.ts
packages/keyring/src/keyring.ts
packages/keyring/src/pair/decode.ts
packages/keyring/src/types.ts

Something that came up in https://github.com/polkadot-js/common/issues/915#issuecomment-791218646 - it would be useful to allow the addition of raw public/secret pairs as to the keyring well (which actually encapsulates the createPair completely, i.e. no need to use it separately)

Allow for addition of raw pairs to the keyring

---

packages/util/src/logger.ts

Webpack 5 now removed node shims, so when building for browser bundle external packages are recommended to either provide a `browser` field in `package.json` to point to umd package (which @polkadot.js/utils doesn't have) or add extra check for `process` 
https://webpack.js.org/migrate/5/
And unfortunately babel doesn't transpile optional chaining here correctly it seems as it still throws error that process is undefined 
`const maxSize = parseInt(((_process = process) === null || _process === void 0 ? void 0 : (_process$env = _process.env) === null || _process$env === void 0 ? void 0 : _process$env.DEBUG_MAX) || '-1', 10);`

Extra check for process for browser bundles

---

packages/util/src/logger.spec.ts
packages/util/src/logger.ts

Projects that make use of https://www.npmjs.com/package/debug may rely on `DEBUG` env to specify a set debuggers to use, which may include wildcards and exclusion groups (https://www.npmjs.com/package/debug#wildcards), for example:
```
DEBUG=*,-api:*
```
_(use all debuggers **except** those that begin with `api:`)_
```
DEBUG=api:*
```
_(use all debuggers that begin with `api:`)_
Currently it's not possible to exclude loggers created by `@polkadot` packages or include only one of the loggers, whithout including all others that start with the same set of characters.
This PR is a suggestion of how this problem may be addressed.

logger - wildcard include/exclude with DEBUG env

---

CHANGELOG.md
packages/util-crypto/src/address/checksum.spec.ts
packages/util-crypto/src/address/decode.spec.ts
packages/util-crypto/src/address/encode.spec.ts

Sanity checks for https://github.com/polkadot-js/common/issues/962
All fine, so not an ss58 issue on the encoders

Add additional 2-byte ss58 tests (verification)

---

CHANGELOG.md
packages/util-crypto/src/hd/ledger/index.spec.ts
packages/util-crypto/src/hd/ledger/index.ts
packages/util-crypto/src/hd/ledger/master.ts

Addresses issues for Ledger using non-standard/extended mnemonics such as https://github.com/polkadot-js/apps/issues/5014 & https://github.com/jacogr/sample-ledger-ed25519/issues/1

Allow hdLedger derivation with optional 25th word password

---

packages/util-crypto/src/nacl/seal.ts

Was using naclSeal and noticed a wrong import in the docs. Thought might change it to remove confusion.

docs: fix typo in naclSeal docs.

---

packages/hw-ledger/src/defaults.ts
packages/networks/src/defaults.ts

Adds Ledger support for Edgeware, which should be supported by the Zondax library as of https://github.com/Zondax/ledger-substrate-js/pull/35.

Add Edgeware ledger app

---

package.json
packages/keyring/src/pair/index.spec.ts
packages/keyring/src/pair/index.ts
packages/keyring/src/pair/nobody.ts
packages/keyring/src/types.ts
packages/util-crypto/package.json
packages/util-crypto/src/nacl/convertKey.ts
packages/util-crypto/src/nacl/index.ts
yarn.lock

Ref: https://github.com/polkadot-js/common/issues/1068
- 1 dependency added to 'util-crypto' - `ed2curve` by the author of tweetnacl.js 
- tests included
- covers sr25519 & ed25519, secp256k1 to be added.

Add in ability to encrypt/decrypt msg with keyring

---

packages/hw-ledger/src/defaults.ts
packages/networks/src/defaults.ts

mutate the variables that will allow the polkadot js app frontend to enable ledger support for the nodle chain

add nodle ledger specs

---

CHANGELOG.md
packages/util/src/string/camelCase.spec.ts
packages/util/src/string/camelCase.ts

Re-introduce old-style word splits based on TLA ordering.
Closes https://github.com/polkadot-js/common/issues/1286

Preserve all-caps word splits in `stringCamelCase`

---

packages/x-randomvalues/src/react-native.ts

As per https://github.com/polkadot-js/common/issues/1422#issuecomment-1068220333 (due to the current expo versions, cater for both old and new)

Cater for Expo v41+ in getRandomValues

---

packages/hw-ledger/src/defaults.ts
packages/networks/src/defaults/genesis.ts
packages/networks/src/defaults/ledger.ts

I list the changes here:
- Nodle has changed chain, now with a new parachain. I added it but I left the other one, just for compatibility some time. It should be removed in some time. EDIT: I asked the team and they confirmed that the old chain has been halted, so I removed it from those files.
- I added Astar and Polkadex to KnownLedger
I just have one doubt. The name of the keys (so `astar`, `nodle-para`, `nodle-chain`) is the name that I can see in polkadot.js.org/apps at the left side, just below the name, right? So `<name>/<spec version>`? In this case polkadex name is `node` that probably is so general, but I added a comment to recognize it.
Thanks!

some changes to KnownLedger

---

packages/util/src/object/property.spec.ts
packages/util/src/object/property.ts

Makes some stuff like https://github.com/polkadot-js/api/pull/5087 possible (and also aligns with lazy by not capturing the outer this)

Pass internal this through on objectProperties

---

CHANGELOG.md
packages/util/src/has.spec.ts
packages/util/src/has.ts
packages/util/src/logger.ts

As per https://github.com/polkadot-js/api/issues/5359 having the naked checks trips up some bundlers and they would auto-add the Buffer or process polyfills. (These are not needed for operation, the detection is there to enable specific features)

Adjust has{Buffer, Process} checks w/ globalThis

---

packages/hw-ledger/src/defaults.ts
packages/networks/src/defaults/genesis.ts
packages/networks/src/defaults/ledger.ts

Nodle's known network name in [ss58-registry.json](https://github.com/paritytech/ss58-registry/blob/main/ss58-registry.json) is "nodle". In contrast "nodle-para" is the runtime's spec name shared between nodle's main parachain on Polkadot and nodle's test parachain on Rococo. This change is necessary for the logic in [networks/src/interfaces.ts](https://github.com/polkadot-js/common/blob/master/packages/networks/src/interfaces.ts) to flag Nodle as a selectable network to interact with Ledger. This issue is impacting polkadot-js/apps in not listing Nodle in the modal dialog for creating a new Ledger account.
This fix needs to be checked by @carlosala in case it may have any side-effect on the actual function of connecting to Nodle's app on Ledger.

fix Nodle's known network name

---

packages/util/src/u8a/toU8a.ts

This is actually a slight bug that was hidden by the Jest test environment (didn't affect operation, however was not as intended)

Ensure u8aToU8a(Buffer) return non-Buffer instance

---

packages/util/src/format/formatBalance.spec.ts

Before this we actually depended on the test order, instead of each `it`-block being independent.

Reset global formatBalance test side effects

---

packages/hw-ledger-transports/src/browser.ts
packages/hw-ledger-transports/src/node.ts
packages/hw-ledger-transports/src/types.ts
packages/keyring/src/index.spec.ts
packages/keyring/src/keyring.ts
packages/keyring/src/pair/decode.ts
packages/keyring/src/pair/encode.ts
packages/keyring/src/pair/index.ts
packages/keyring/src/pairs.ts
packages/keyring/src/testing.ts
packages/keyring/src/testingPairs.ts
packages/util-crypto/src/address/check.ts
packages/util-crypto/src/address/decode.ts
packages/util-crypto/src/address/derive.ts
packages/util-crypto/src/address/encode.ts
packages/util-crypto/src/address/encodeDerived.ts
packages/util-crypto/src/address/encodeMulti.ts
packages/util-crypto/src/address/evmToAddress.ts
packages/util-crypto/src/address/is.ts
packages/util-crypto/src/address/setSS58Format.ts
packages/util-crypto/src/address/sort.ts
packages/util-crypto/src/address/validate.ts
packages/util-crypto/src/json/constants.ts
packages/util-crypto/src/json/decrypt.ts
packages/util-crypto/src/json/decryptData.ts
packages/util-crypto/src/json/encrypt.ts
packages/util-crypto/src/json/encryptFormat.ts
packages/util/src/test/performance.ts
tsconfig.base.json

Follow-up for https://github.com/polkadot-js/api/issues/5524 (when we finally enable `"moduleResolution": "nodenext"` in `@polkadot/dev`)

Align tsconfig to allow moduleResolution: nodenext

---

CHANGELOG.md
packages/util-crypto/src/base32/decode.spec.ts
packages/util-crypto/src/base32/helpers.ts
packages/util-crypto/src/base32/validate.spec.ts
packages/util-crypto/src/base58/decode.spec.ts
packages/util-crypto/src/base64/decode.spec.ts

Found as part of https://github.com/polkadot-js/common/pull/1785 (where those utils mismatches with our inputs)
Additionally the underlying base* decoders do accept and decode it correctly.

Allow empty string as valid base32/base58/base64 decoder input

---

packages/util-crypto/src/mnemonic/generate.spec.ts
packages/util-crypto/src/mnemonic/generate.ts
packages/util-crypto/src/mnemonic/toEntropy.spec.ts
packages/util-crypto/src/mnemonic/toEntropy.ts
packages/util-crypto/src/mnemonic/toMiniSecret.spec.ts
packages/util-crypto/src/mnemonic/toMiniSecret.ts
packages/util-crypto/src/mnemonic/toMiniSecretCmp.spec.ts
packages/util-crypto/src/mnemonic/validate.spec.ts
packages/util-crypto/src/mnemonic/validate.ts

Part 2 of https://github.com/polkadot-js/common/issues/1804

Allow wordlist? param to mnemonic* functions

---

CHANGELOG.md
packages/util/src/is/riscv.spec.ts
packages/util/src/is/riscv.ts

Closes https://github.com/polkadot-js/common/issues/1893

Adjust `isRiscV` helper to check for `PVM\0` bytes

---

packages/util/src/versionDetect.spec.ts
packages/util/src/versionDetect.ts

These warnings are really annoying for dual esm and cjs packages and take up most of the terminal making it hard to debug.
```
(Use `node --trace-warnings ...` to show where the warning was created)
(node:18971) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
@polkadot/util has multiple versions, ensure that there is only one installed.
Either remove and explicitly install matching versions or dedupe using your package manager.
The following conflicting packages were found:
esm 12.3.2	node_modules/@polkadot/util/
cjs 12.3.2	node_modules/@polkadot/util/cjs
@polkadot/types has multiple versions, ensure that there is only one installed.
Either remove and explicitly install matching versions or dedupe using your package manager.
The …
```

Get rid of warnings for dual esm and cjs packages of the same version

---

packages/hw-ledger/src/LedgerGeneric.ts
packages/hw-ledger/src/constants.ts

This removes the `slip44` arg from the constructor of `LedgerGeneric`.  It's not necessary and just flat out breaks the ledger interface for all chains but polkadot. This was an oversight by me, and needs to just be the polkadot slip44 for all chains.
That being said for this reason I am considering this a patch.

Remove slip44, and replace with POLKADOT_SLIP

---

packages/hw-ledger/src/LedgerGeneric.ts
packages/hw-ledger/src/constants.ts

Revert: https://github.com/polkadot-js/common/commit/527b4f0eeb5be06e37912e02a5909b1c56ebf90b
I came to the conclusion that it is okay to allow the Slip44 to be passed in. I think this will be specifically useful for the migration app.

Revert slip44 change

---

packages/hw-ledger/src/defaults.ts
packages/networks/src/defaults/ledger.ts

Bittensor has applied the runtime upgrade for the generic Ledger app integration.
This PR adds it to the mapping of `genericLedgerApps`

Add bittensor to genericLedgerApps

---

packages/hw-ledger/src/defaults.ts
packages/networks/src/defaults/genesis.ts
packages/networks/src/defaults/ledger.ts

[Frequency](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2F0.rpc.frequency.xyz#/explorer) has the CheckMetadataHash extension on Mainnet and supports the generic Ledger application. This PR is to enable it in polkadot-js apps and extension.

Add Frequency to the Generic Ledger App

---

.github/workflows/pr-any.yml
packages/util/src/format/getSeparator.spec.ts
packages/util/src/format/getSeparator.ts

closes: https://github.com/polkadot-js/common/issues/1964 Changes the CI to be back to lts/*

Fix toLocaleString for v22.12

---

.github/workflows/pr-any.yml
package.json
yarn.lock

This parallelizes tests increasing testing performance heavily.
Note:
This also corrects the deno build process. It started to fail for everything 1.x and 2.x, and this patch ensures the Buffer is included in each build where necessary as an import.

Bump dev to 0.83.2

---

packages/keyring/src/index.spec.ts
packages/keyring/src/keyring.ts
packages/keyring/src/types.ts
packages/util-crypto/src/key/extractSuri.spec.ts
packages/util-crypto/src/key/extractSuri.ts

This pull request addresses part 3 of issue #1804.  It introduces the capability to create `KeyringPair` instances using custom mnemonic wordlists, enhancing support for various languages and improving flexibility in key pair generation.
Key Changes:
- Added functionality to specify custom BIP-39 mnemonic wordlists during KeyringPair creation using `addFromMnemonic()`, `addFromUri()` and `createFromUri()`.
- Updated relevant documentation to reflect the new feature.
- Included tests to ensure compatibility with different mnemonic wordlists.
closes #1804

Enable KeyringPair Creation with Custom Mnemonic Wordlists

---

packages/x-ws/src/node.ts

Addresses #1975. Starting from Node.js 22, the built in WebSocket implementation does not provide detailed error messages (e.g., `ECONNREFUSED`, `ETIMEDOUT`). This can cause issues when handling disconnections and reconnections in `polkadot-js/api`, as the errors are too generic to detect connection failures properly.
This PR forces the use of the ws library in Node.js 22+. This temporarily fixes the issue, until the  Node.js native WebSocket become mature enough to handle such errors.

Fix: Use ws library in Node.js 22+ for Better WebSocket Error Handling

---

packages/x-ws/src/node.ts

Fixes an issue where the `WebSocket` type was inconsistently resolved as either the ws library's WebSocket implementation or the native `WebSocket`, leading to type mismatches.

Cast ws as global.WebSocket

---

packages/util/src/object/spread.ts

This PR updates the `objectSpread` function to better handle special object properties. The changes include:
- Added property filtering to maintain consistent object structure
- Improved handling of Map and regular object sources
- Enhanced object property copying mechanism
- Updated documentation to reflect the new behavior
These changes ensure more predictable object property spreading behavior across different input types.

Improve objectSpread function property handling

---

packages/util/src/u8a/toU8a.spec.ts
packages/util/src/u8a/toU8a.ts

This PR introduces an opt-in `strict` parameter to the `u8aToU8a` function to prevent silently converting `null` or `undefined` inputs into empty `Uint8Array` instances.
While working with this function, we noticed that passing `null` or `undefined` was producing empty arrays instead of throwing errors, leading to hard-to-trace issues. This behavior caused 134 test failures. Instead of modifying every test and potentially introducing inconsistencies, we chose to add a strict checking mode.
- Adds a `strict` boolean parameter (default: `false`) to `u8aToU8a`.
- When `strict` is enabled, the function throws an error if the input is `null` or `undefined`.
- Default behavior is preserved to maintain backward compatibility.
This approach allows developers to opt into stricter input validation …

Add Optional Strict Input Checking to `u8aToU8a`
