docs/README.md
src/logger.js
src/logger.spec.js
src/types.js

Closes https://github.com/polkadot-js/util/issues/59

Expand logger for debug

---

flow-typed/bs58.js
package.json
packages/util-keyring/package.json
packages/util-keyring/src/address/decode.js
packages/util-keyring/src/address/decode.spec.js
packages/util-keyring/src/address/encode.js
packages/util-keyring/src/address/encode.spec.js
packages/util-keyring/src/address/index.js
packages/util-keyring/src/index.js
packages/util-keyring/src/pair/index.js
packages/util-keyring/src/testingPairs.js
packages/util-keyring/src/types.js
packages/util/package.json
packages/util/src/is/bn.js
packages/util/src/is/bn.spec.js
packages/util/src/is/index.js
packages/util/src/is/observable.js
packages/util/src/is/observable.spec.js
yarn.lock

Closes https://github.com/polkadot-js/util/issues/121

Add keyring publicKey <-> address

---

package.json
packages/util-triedb/src/temp/pairs.js
packages/util-triedb/src/temp/types.js
packages/util/package.json
packages/util/src/logger.js
packages/util/src/logger.spec.js
yarn.lock

For now it only does the identifying part (keeping console.log to do magic with the actual values)

Allow logging with colors (based on type)

---

.travis.yml
package.json
yarn.lock

Prevents older versions https://github.com/polkadot-js/apps/pull/78

Add yarn & node to engines

---

package.json
packages/util-keyring/src/address/decode.ts
packages/util-keyring/src/pairs.ts
packages/util/package.json
packages/util/src/is/hex.ts
packages/util/src/is/observable.ts
yarn.lock

Update isHex & isObservable, closes https://github.com/polkadot-js/common/issues/143

Use bn types from @types

---

packages/type-extrinsics/src/consensus.ts
packages/type-params/src/encode/type/index.ts
packages/type-params/src/encode/type/keyValue.spec.js
packages/type-params/src/encode/type/keyValue.ts

Part of https://github.com/polkadot-js/apps/issues/17

Support KeyValue encoding/decoding (storage)

---

packages/type-params/src/decode/index.spec.js
packages/type-params/src/decode/value/keyValue.spec.js
packages/type-params/src/decode/value/keyValue.ts

- Fix offset for value length was wrong
- Add tests for KeyValue
Found as part of https://github.com/polkadot-js/apps/pull/131

Fix KeyValue decoding (length offset)

---

package.json
packages/type-params/src/decode/value/code.ts
yarn.lock

- Code length-prefixed, Closes https://github.com/polkadot-js/common/issues/166
- democracy.second types, Closes https://github.com/polkadot-js/common/issues/167

Decode code correctly (length-prefixed)

---

package.json
packages/type-extrinsics/src/democracy.ts
packages/type-params/src/decode/value/code.ts
yarn.lock

democracy.second types, Closes #167 (Previous PR didn't include this commit)

democracy.second(PropIndex)

---

packages/type-extrinsics/src/staking.ts

Closes https://github.com/polkadot-js/common/issues/156

Add staking.(un)nominate

---

packages/type-extrinsics/src/codec/encode/call.ts
packages/type-params/src/encode/type/index.ts
packages/type-params/src/method.ts
packages/type-params/src/section.ts
packages/util-rlp/src/encoder/toU8a.ts
packages/util-rlp/test/getTests.ts
packages/util/src/bn/toU8a.spec.js
packages/util/src/bn/toU8a.ts
packages/util/src/logger.spec.js
packages/util/src/logger.ts
packages/util/src/u8a/toBn.spec.js
packages/util/src/u8a/toBn.ts

First step towards https://github.com/polkadot-js/common/issues/179

Make isLe required in conversion

---

packages/type-params/src/decode/value/bn.ts

Fixes issues with new Rust Node RPC layer

Decode null as BN without failing

---

packages/db-diskdown/package.json
packages/db-diskdown/src/index.ts
packages/db-diskdown/src/store/Combined.ts
yarn.lock

It should be handled at a higher (more-optimal) level

Remove db-diskdown LRU

---

packages/util/src/string/camelCase.spec.js
packages/util/src/string/camelCase.ts

Fix camel case

---

package.json
packages/db/src/FileFlatDb/index.ts
packages/trie-hash/src/encode/hexPrefix.ts
packages/trie-hash/src/encode/pairs.ts
packages/util-rlp/src/decoder/listLong.ts
packages/util-rlp/src/decoder/listShort.ts
yarn.lock

Reported by @chevdor on using the libraries via npm (with a different TS setup)
In short, where we only do `const something = []` TS _sometimes_ (depending on config) would not see those as `any[]` but rather `never[]`. So be explicit where we define arrays.

Explicit Array<any>

---

packages/keyring/src/index.ts
packages/keyring/src/pair/index.ts
packages/keyring/src/types.d.ts

Related to fixing https://github.com/polkadot-js/apps/pull/446

Expose address decoding/encoding on keyring

---

packages/keyring/src/pair/index.ts
packages/keyring/src/pair/toJson.ts
packages/keyring/src/pair/types.d.ts

Related to https://github.com/polkadot-js/apps/issues/445

Encode address as/when required

---

.codeclimate.yml
packages/util/src/u8a/toHex.ts

Optimise for very long arrays, as per https://github.com/polkadot-js/apps/pull/465

Optimise u8aToHex function (32% of original time)

---

packages/util/src/index.ts
packages/util/src/logger.ts
packages/util/src/polyfill.ts
packages/util/src/string/polyfill/padding.spec.ts
packages/util/src/string/polyfill/padding.ts

Related to https://github.com/polkadot-js/api/issues/481

Polyfills for RN support

---

package.json
packages/util/src/compact/fromU8a.spec.ts
packages/util/src/compact/fromU8a.ts
packages/util/src/compact/toU8a.spec.ts
packages/util/src/compact/toU8a.ts
yarn.lock

Part of https://github.com/polkadot-js/api/issues/505

Fix large-value Compact encoding

---

packages/keyring/src/index.spec.ts
packages/util-crypto/src/index.ts
packages/util-crypto/src/schnorrkel/index.ts
packages/util-crypto/src/schnorrkel/keypair/fromSeed.spec.ts
packages/util-crypto/src/schnorrkel/ready.ts
packages/util-crypto/src/schnorrkel/schnorrkel-js/schnorrkel_js.d.ts
packages/util-crypto/src/schnorrkel/schnorrkel-js/schnorrkel_js.js
packages/util-crypto/src/schnorrkel/schnorrkel-js/schnorrkel_js_bg.js
packages/util-crypto/src/schnorrkel/signVerify.spec.ts

- Closes https://github.com/polkadot-js/common/issues/305
- Related to https://github.com/paritytech/schnorrkel-js/issues/7

Async schnorrkel init

---

packages/util-crypto/package.json
packages/util-crypto/src/schnorrkel/schnorrkel-js/schnorrkel_js.js
packages/util-crypto/src/schnorrkel/schnorrkel-js/schnorrkel_js_bg.js
yarn.lock

Allow proper promise failure

---

packages/util-crypto/src/schnorrkel/ready.spec.ts
packages/util-crypto/src/schnorrkel/schnorrkel-js/schnorrkel_js.js
packages/util-crypto/src/schnorrkel/schnorrkel-js/schnorrkel_js_bg.js

null on WASM non-available

---

packages/keyring/src/pair/index.spec.ts
packages/keyring/src/pair/index.ts

Expand setMeta to actually set (with tests)

---

package.json
packages/util-crypto/package.json
packages/util-crypto/src/index.ts
packages/util-crypto/src/secp256k1/index.ts
packages/util-crypto/src/secp256k1/recover.ts
yarn.lock

Closes https://github.com/polkadot-js/common/issues/296

Add secp256k1Recover

---

packages/util-crypto/package.json
packages/util-crypto/src/mnemonic/generate.spec.ts
packages/util-crypto/src/mnemonic/generate.ts
packages/util-crypto/src/mnemonic/index.ts
packages/util-crypto/src/mnemonic/toEntropy.spec.ts
packages/util-crypto/src/mnemonic/toEntropy.ts
packages/util-crypto/src/mnemonic/toSeedEntropy.spec.ts
packages/util-crypto/src/mnemonic/toSeedEntropy.ts
packages/util-crypto/src/schnorrkel/keypair/fromSeed.spec.ts
packages/util-crypto/src/schnorrkel/keypair/testing.ts
yarn.lock

- Closes https://github.com/polkadot-js/common/issues/340

Generate mnemonic via entropy (use in sr25519)

---

CHANGELOG.md
lerna.json
package.json
packages/chainspec/package.json
packages/db/package.json
packages/keyring/package.json
packages/trie-codec/package.json
packages/trie-db/package.json
packages/trie-hash/package.json
packages/util-crypto/package.json
packages/util-rlp/package.json
packages/util/package.json
yarn.lock

Swap to publishing -beta.x on merge

---

packages/util-crypto/package.json
packages/util-crypto/src/schnorrkel/deriveHard.ts
packages/util-crypto/src/schnorrkel/deriveSoft.ts
packages/util-crypto/src/schnorrkel/keypair/fromSeed.ts
packages/util-crypto/src/schnorrkel/polyfill.ts
packages/util-crypto/src/schnorrkel/ready.ts
packages/util-crypto/src/schnorrkel/sign.ts
packages/util-crypto/src/schnorrkel/verify.ts
yarn.lock

(Instead of the now-archived schnorrkel-js)

Use wasm-schnorrkel package

---

CHANGELOG.md
packages/keyring/src/index.ts
packages/util/src/assertSingletonPackage.spec.ts
packages/util/src/assertSingletonPackage.ts
packages/util/src/index.ts

For https://github.com/polkadot-js/api/issues/795

Add singleton package assertion (& add to keyring)

---

packages/keyring/src/address/decode.spec.ts
packages/keyring/src/address/decode.ts
packages/keyring/src/address/encode.spec.ts
packages/keyring/src/address/encode.ts
packages/keyring/src/address/setPrefix.spec.ts
packages/keyring/src/address/sshash.ts
packages/keyring/src/index.spec.ts
packages/keyring/src/index.ts
packages/keyring/src/pair/toJson.spec.ts
packages/keyring/src/suri.spec.ts
packages/keyring/src/testingPairs.spec.ts
packages/keyring/src/types.ts

Implements new checksum format from https://github.com/paritytech/substrate/pull/2141

ss58 Checksum updates

---

CHANGELOG.md
packages/util/src/format/formatBalance.spec.ts
packages/util/src/format/formatBalance.ts
packages/util/src/format/formatDecimal.spec.ts
packages/util/src/format/formatDecimal.ts
packages/util/src/format/formatElapsed.spec.ts
packages/util/src/format/formatElapsed.ts
packages/util/src/format/formatNumber.ts
packages/util/src/format/index.ts
packages/util/src/format/si.ts
packages/util/src/format/types.ts
packages/util/src/index.ts
packages/util/src/is/index.ts
packages/util/src/is/testChain.spec.ts
packages/util/src/is/testChain.ts

Part of https://github.com/polkadot-js/ui/issues/108

Pull in functions from ui-util

---

CHANGELOG.md
packages/keyring/src/index.spec.ts
packages/keyring/src/index.ts

Closes https://github.com/polkadot-js/common/issues/394

Fix addFromMnemonic

---

package.json
packages/keyring/src/testing.ts
packages/keyring/src/testingPairs.spec.ts
yarn.lock

- Additional stash for commonly-used accounts, without going overboard and spamming with all that is available
- Closes https://github.com/polkadot-js/apps/issues/1117

Add Bob//stash to test keyring

---

CHANGELOG.md
lerna.json
packages/chainspec/package.json
packages/db/package.json
packages/keyring/package.json
packages/trie-codec/package.json
packages/trie-db/package.json
packages/trie-hash/package.json
packages/util-crypto/package.json
packages/util-rlp/package.json
packages/util/package.json
packages/util/src/format/formatBalance.spec.ts
packages/util/src/format/formatBalance.ts
packages/util/src/format/formatDecimal.spec.ts
packages/util/src/format/formatDecimal.ts
packages/util/src/format/formatNumber.spec.ts

Also bumps to 0.92 (barring mishaps, no addition features planned for this point release)

Cater for negative values in number formats

---

CHANGELOG.md
docs/examples/keyring/01_create_account/index.js
docs/examples/keyring/02_load_accounts/index.js
packages/keyring/src/address/decode.spec.ts
packages/keyring/src/address/encode.spec.ts
packages/keyring/src/index.spec.ts
packages/keyring/src/keyring.ts
packages/keyring/src/pair/index.spec.ts
packages/keyring/src/pair/index.ts
packages/keyring/src/pair/nobody.ts
packages/keyring/src/pairs.ts
packages/keyring/src/suri.spec.ts
packages/keyring/src/testingPairs.spec.ts
packages/keyring/src/testingPairs.ts
packages/keyring/src/types.ts

Modify the KeyringPair interface to be consistent with [changes](https://github.com/polkadot-js/ui/pull/144) made to `@polkadot/ui-keyring`

Simplify @polkadot/keyring KeyringPair

---

package.json
packages/trie-codec/src/decode.ts
packages/trie-codec/src/encode.ts
packages/trie-codec/src/stream/createBranch.ts
packages/trie-db/src/constants.ts
yarn.lock

Additionally bump to latest @polkadot/dev

Small trie-codec optimizations (tested as-is in client)

---

package.json
packages/chainspec/package.json
packages/db/package.json
packages/keyring/package.json
packages/trie-codec/package.json
packages/trie-db/package.json
packages/trie-hash/package.json
packages/util-crypto/package.json
packages/util-rlp/package.json
packages/util/package.json
yarn.lock

Have not bumped BN.js to 5.0 (yet), there are breaking changes

Bump deps (incl. Babel 7.5)

---

packages/db/src/engines/MemoryDb.spec.ts
packages/util/src/compact/toU8a.spec.ts
packages/util/src/polyfill/fill.spec.ts
packages/util/src/polyfill/setPrototypeOf.spec.ts

Some small additional tests, basically for some lesser-used functionality

Some additional small tests

---

docs/examples/keyring/03_validate_address/README.md
docs/examples/keyring/03_validate_address/index.js
docs/examples/keyring/03_validate_address/package.json

Let me know if this should be in the utils folder

added check if valid address to docs

---

package.json
packages/util-crypto/src/address/check.spec.ts
packages/util-crypto/src/address/check.ts
packages/util-crypto/src/address/decode.spec.ts
packages/util-crypto/src/address/encode.spec.ts
packages/util-crypto/src/address/index.ts
packages/util-rlp/src/decoder/safeParseInt.spec.ts

Add address check function

---

CHANGELOG.md
packages/util/src/format/formatBalance.spec.ts
packages/util/src/format/formatBalance.ts

Closes https://github.com/polkadot-js/common/issues/447

formatBalance allows Compact inputs

---

CHANGELOG.md
package.json
packages/util/src/assertSingletonPackage.spec.ts
packages/util/src/assertSingletonPackage.ts
yarn.lock

Helps in cases like https://github.com/polkadot-js/extension/issues/119

assertSingleton warns, not throws

---

packages/util/src/format/formatBalance.ts
packages/util/src/format/si.ts
packages/util/src/types.ts

For improvements to InputNumber.tsx

Expose SiDef type

---

CHANGELOG.md
packages/util/src/format/formatDate.spec.ts
packages/util/src/format/formatDate.ts
packages/util/src/format/index.ts
packages/util/src/logger.ts

As per https://github.com/polkadot-js/common/pull/530#issuecomment-586574602

Move date formatter to format

---

CHANGELOG.md
packages/keyring/src/index.spec.ts
packages/keyring/src/keyring.ts
packages/keyring/src/pair/index.spec.ts
packages/keyring/src/pair/index.ts
packages/keyring/src/testing.ts
packages/keyring/src/types.ts
packages/util-crypto/src/address/setSS58Format.ts

Closes https://github.com/polkadot-js/common/issues/420

Use ss58 format on keyring for the keyring only

---

CHANGELOG.md
packages/util-crypto/src/address/check.ts
packages/util-crypto/src/address/checkChecksum.ts
packages/util-crypto/src/address/decode.ts
packages/util-crypto/src/address/index.ts
packages/util-crypto/src/index.ts
packages/util-crypto/src/signature/index.ts
packages/util-crypto/src/signature/verify.spec.ts
packages/util-crypto/src/signature/verify.ts
packages/util-crypto/src/types.ts
packages/util/src/u8a/fixLength.ts
packages/util/src/u8a/toBuffer.ts
packages/util/src/u8a/toString.ts
packages/util/src/u8a/toU8a.ts

Closes #550 
WIP, still needs tests

Add signatureVerify

---

packages/keyring/src/pair/index.spec.ts
packages/keyring/src/pair/index.ts

Throws an error when signing with a locked keypair

---

CHANGELOG.md
package.json
packages/util-crypto/src/address/index.ts
packages/util-crypto/src/address/keyMulti.spec.ts
packages/util-crypto/src/address/keyMulti.ts
packages/util-crypto/src/address/keySub.spec.ts
packages/util-crypto/src/address/keySub.ts
packages/util/src/u8a/concat.ts
yarn.lock

Create createKeyMulti & createKeySub for utility (util-crypto)

---

docs/examples/util-crypto/04_generate_multisig_address/README.md
docs/examples/util-crypto/04_generate_multisig_address/index.js
docs/examples/util-crypto/04_generate_multisig_address/package.json

Adds an example of how to use `createKeyMulti`.

Add example for multisig address creation

---

packages/util-crypto/src/blake2/asU8a.spec.ts
packages/util-crypto/src/blake2/asU8a.ts

Closes https://github.com/polkadot-js/common/issues/613

Fix blake2 U8a JS with hex inputs

---

CHANGELOG.md
packages/util-crypto/src/address/decode.spec.ts
packages/util-crypto/src/address/derive.spec.ts
packages/util-crypto/src/address/derive.ts
packages/util-crypto/src/address/encodeDerived.ts
packages/util-crypto/src/address/index.ts
packages/util-crypto/src/schnorrkel/derivePublic.ts
packages/util-crypto/src/schnorrkel/index.ts

Closes https://github.com/polkadot-js/common/issues/648

Add deriveAddress

---

CHANGELOG.md
packages/util-crypto/src/ethereum/encode.spec.ts
packages/util-crypto/src/ethereum/encode.ts
packages/util-crypto/src/ethereum/index.ts
packages/util-crypto/src/ethereum/isAddress.spec.ts
packages/util-crypto/src/ethereum/isAddress.ts
packages/util-crypto/src/ethereum/isChecksum.ts
packages/util-crypto/src/ethereum/isCheksum.spec.ts
packages/util-crypto/src/index.ts

Moves towards https://github.com/polkadot-js/common/issues/656

Ethereum address utils

---

CHANGELOG.md
packages/keyring/src/index.spec.ts
packages/keyring/src/keyring.ts
packages/keyring/src/pair/index.ts
packages/keyring/src/types.ts

Root cause for https://github.com/polkadot-js/apps/issues/3765 (replaces https://github.com/polkadot-js/apps/pull/3766, however there needs to be error checking there now)

Keypair recoding should decode, then encode

---

CHANGELOG.md
packages/util/src/format/formatBalance.spec.ts
packages/util/src/format/formatBalance.ts

Closes https://github.com/polkadot-js/common/issues/690

Change decimals, move unit

---

packages/keyring/README.md

remove doc broken link

---

packages/util-crypto/README.md
packages/util/README.md

Prep for https://github.com/polkadot-js/common/issues/671

Remove SUMMARY.md is prep for rework

---

.github/workflows/ss58-registry.yml

Hopefully will solve https://github.com/polkadot-js/common/issues/706
... Well, will know tomorrow, it _is_ currently outdated :)

Create issue on failure of ss58 nightly run

---

.github/ss58-check.md
packages/networks/src/index.ts

Closes https://github.com/polkadot-js/common/issues/734

Add Totem (ss58 = 14)

---

.github/ss58-check.md
.github/workflows/pr-any.yml
packages/networks/src/index.ts

Add Synesthesia to networks

---

packages/util-crypto/package.json
packages/util/package.json
yarn.lock

Dedupe bn.js

---

packages/util/src/logger.spec.ts
packages/util/src/logger.ts
packages/x-textdecoder/src/node.ts
packages/x-textencoder/src/node.ts
packages/x-ws/src/node.ts

Closes #491 
Closes https://github.com/polkadot-js/common/issues/683
Replaces https://github.com/polkadot-js/common/pull/769

Limit logger size via DEBUG_MAX

---

packages/util/src/index.ts
packages/util/src/memoize.spec.ts
packages/util/src/memoize.ts
packages/util/src/types.ts

Closes https://github.com/polkadot-js/common/issues/804

Add memoize util

---

packages/networks/src/index.ts

Adds details needed for Polymesh ledger integration.

Add Polymesh Ledger Integration

---

packages/util-crypto/package.json
packages/util-crypto/src/schnorrkel/index.ts
packages/util-crypto/src/schnorrkel/sign.ts
packages/util-crypto/src/schnorrkel/verify.ts
packages/util-crypto/src/schnorrkel/vrfSign.ts
packages/util-crypto/src/schnorrkel/vrfSignVerify.spec.ts
packages/util-crypto/src/schnorrkel/vrfVerify.ts
yarn.lock

Closes https://github.com/polkadot-js/common/issues/840

Add schnorrkelVrf{Sign, Verify} functions

---

packages/hw-ledger/src/index.ts

This aligns with the upstream ss58 registry and downstream ledger packages.

Update ledger key to polymesh (from polymath)

---

packages/keyring/src/suri.spec.ts

Part of https://github.com/polkadot-js/common/issues/849
Weirdly it matches. So may indeed be an UI funny.

EDCSA derive test

---

packages/util/src/format/formatBalance.spec.ts
packages/util/src/format/formatBalance.ts

Needed for https://github.com/polkadot-js/api/pull/3093
Needed for polkadot-js/apps#4078

Allow formatBalance to take array defaults

---

packages/networks/src/index.ts

Closes https://github.com/polkadot-js/common/issues/878

Align ss58 with master registry

---

CHANGELOG.md
packages/keyring/src/index.spec.ts
packages/keyring/src/pair/index.spec.ts
packages/keyring/src/pair/index.ts
packages/keyring/src/pair/vrf.spec.ts
packages/keyring/src/types.ts
packages/util-crypto/src/signature/verify.spec.ts
packages/util-crypto/src/signature/verify.ts
packages/util-crypto/src/types.ts

As per https://github.com/polkadot-js/common/pull/858#issuecomment-781289330

Pass publicKey through on verify

---

package.json
packages/hw-ledger-transports/package.json
packages/networks/src/index.ts
packages/x-randomvalues/package.json
packages/x-rxjs/package.json
yarn.lock

Closes https://github.com/polkadot-js/common/issues/933

Add ss58 252

---

package.json
packages/networks/src/index.spec.ts
packages/x-fetch/package.json
packages/x-global/package.json
yarn.lock

As per https://github.com/polkadot-js/common/pull/935#issuecomment-815539836

Check for prefix dupes

---

packages/keyring/src/index.spec.ts
packages/keyring/src/keyring.ts

Check for https://github.com/polkadot-js/common/issues/962
... all ok

Keyring verification test for 2-byte ss58

---

CHANGELOG.md
packages/networks/src/substrate.ts

Closes https://github.com/polkadot-js/common/issues/967

Remove ss58 27 prefix

---

packages/networks/src/substrate.ts
packages/util-crypto/src/json/decryptData.ts

Closes https://github.com/polkadot-js/common/issues/970

Align ss58

---

packages/networks/src/defaults.ts

Unfortunately first launch failed. This should be good.

Add HydraDX Snakenet Gen3-1

---

CHANGELOG.md
package.json
packages/networks/src/substrate.ts
yarn.lock

Closes https://github.com/polkadot-js/common/issues/982

Sync with Substrate ss58 registry

---

packages/networks/src/substrate.ts

Closes https://github.com/polkadot-js/common/issues/989
Closes https://github.com/polkadot-js/common/pull/985

Align ss58 with upstream (+3 entries)

---

CHANGELOG.md
package.json
packages/hw-ledger-transports/package.json
packages/x-randomvalues/package.json
yarn.lock

As per https://github.com/polkadot-js/apps/issues/5406 (& https://github.com/LedgerHQ/ledgerjs/issues/607#issuecomment-853939348)

Bump Ledger WebUsb

---

CHANGELOG.md
packages/util/src/array/index.ts
packages/util/src/array/shuffle.spec.ts
packages/util/src/array/shuffle.ts

As per https://github.com/polkadot-js/apps/pull/5656

arrayShuffle

---

CHANGELOG.md
packages/networks/src/substrate.ts

Closes https://github.com/polkadot-js/common/issues/1028

Sync ss58 with upstream

---

CHANGELOG.md
packages/networks/src/substrate.ts
packages/networks/src/types.ts

Closes https://github.com/polkadot-js/common/issues/1034

ss58 update

---

packages/hw-ledger/src/defaults.ts
packages/networks/src/defaults.ts

Closes https://github.com/polkadot-js/common/issues/1025

Ledger info for Statemine

---

packages/networks/src/substrate.ts

Closes https://github.com/polkadot-js/common/issues/1037

Update ss58 registry

---

CHANGELOG.md
package.json
packages/hw-ledger-transports/package.json
packages/hw-ledger/package.json
packages/keyring/package.json
packages/networks/package.json
packages/networks/src/index.ts
packages/networks/src/interfaces.ts
packages/util-crypto/package.json
packages/util-crypto/src/networks.ts
packages/util/package.json
packages/x-bundle/package.json
packages/x-fetch/package.json
packages/x-global/package.json
packages/x-randomvalues/package.json
packages/x-textdecoder/package.json
packages/x-textencoder/package.json
packages/x-ws/package.json
yarn.lock

Closes https://github.com/polkadot-js/common/issues/1075

Ensure packageInfo from networks doesn't clobber crypto

---

packages/util-crypto/src/address/encodeDerived.ts
packages/util-crypto/src/address/encodeMulti.ts
packages/util-crypto/src/address/keyDerived.ts
packages/util-crypto/src/address/keyMulti.ts
packages/util-crypto/src/key/DeriveJunction.ts
packages/util/src/bn/sqrt.spec.ts
packages/util/src/bn/sqrt.ts
packages/util/src/bn/toBn.ts
packages/util/src/bn/toHex.ts
packages/util/src/bn/toU8a.ts
packages/util/src/compact/toU8a.ts
packages/util/src/format/formatBalance.ts
packages/util/src/format/formatElapsed.ts
packages/util/src/format/formatNumber.ts
packages/util/src/is/bigInt.ts

https://github.com/polkadot-js/api/issues/3868
fix bigint type

fix bigint type

---

packages/networks/src/substrate.ts

Closes https://github.com/polkadot-js/common/issues/1092

Align prefixes with upstream

---

packages/networks/src/substrate.ts

Closes https://github.com/polkadot-js/common/issues/1105

Sync ss58 registry

---

package.json
packages/networks/src/substrate.ts
yarn.lock

Closes https://github.com/polkadot-js/common/issues/1108

Networks:sync

---

packages/networks/scripts/fromSubstrate.mjs
packages/networks/src/crosscheck.spec.ts
packages/networks/src/interfaces.ts

After https://github.com/paritytech/ss58-registry/pull/8
Needed for https://github.com/polkadot-js/common/issues/1104

Update ss58 JSON format handling

---

package.json
packages/hw-ledger/src/types.ts
yarn.lock

As found in https://github.com/polkadot-js/apps/pull/6474

Correct types for Ledger signature

---

package.json
packages/networks/src/substrate.ts
yarn.lock

Closes https://github.com/polkadot-js/common/issues/1162

Sync ss58registry

---

packages/networks/src/defaults.ts

Updates to our latest mainnet hash - needed for h/w wallet integration etc.

Update Polymesh Genesis Hash

---

packages/util/src/hex/stripPrefix.ts
packages/util/src/is/hex.spec.ts
packages/util/src/is/hex.ts

Closes https://github.com/polkadot-js/common/issues/1204

Adjust isHex length check

---

packages/util-crypto/src/base32/helpers.ts

Needs a patch release after https://github.com/polkadot-js/wasm/pull/234

Fix TS import generation

---

package.json
packages/util-crypto/src/base32/helpers.ts
yarn.lock

Pulls in https://github.com/polkadot-js/dev/pull/513
Prevents https://github.com/polkadot-js/common/issues/1225

Bump dev (w/ /src/ check)

---

CHANGELOG.md
packages/util/src/string/camelCase.spec.ts
packages/util/src/string/camelCase.ts

Closes https://github.com/polkadot-js/common/issues/1255
Closes https://github.com/polkadot-js/common/issues/1257

Adjust string{Camel, Pascal}Case

---

CHANGELOG.md
package.json
packages/hw-ledger-transports/package.json
packages/hw-ledger/package.json
packages/keyring/package.json
packages/networks/package.json
packages/util-crypto/package.json
packages/util-crypto/src/noble-hashes/lib/sha3.ts
packages/util/package.json
packages/x-bundle/package.json
packages/x-fetch/package.json
packages/x-global/package.json
packages/x-randomvalues/package.json
packages/x-textdecoder/package.json
packages/x-textencoder/package.json
packages/x-ws/package.json
yarn.lock

8.0.5
Fix expectation missed resulting in https://github.com/polkadot-js/common/issues/1262

Adjust sha3 expectation of `BigInt` availability

---

packages/networks/src/defaults.ts

As simple as in the title! This is our mainnet genesis hash :)

Add Picasso Genesis Hash

---

packages/util/src/bi/consts.ts
packages/x-noble-hashes/src/utils.ts

As per https://github.com/polkadot-js/common/pull/1268#issuecomment-983642146

Adjust for anon

---

packages/util-crypto/src/xxhash/xxhash64.ts
packages/util/package.json
packages/util/src/bi/consts.ts
packages/util/src/bi/toBigInt.ts
packages/util/src/has.ts
packages/util/src/hex/toBigInt.ts
packages/util/src/u8a/toBigInt.ts
packages/x-noble-hashes/src/_sha2.ts
packages/x-noble-hashes/src/_u64.ts
packages/x-noble-hashes/src/blake2b.ts
packages/x-noble-hashes/src/blake2s.ts
packages/x-noble-hashes/src/blake3.ts
packages/x-noble-hashes/src/utils.ts
yarn.lock

Alternative attempt for RN being crazy on BigInt inside functions, aka https://github.com/polkadot-js/common/issues/1262

Use BigInt only via xglobal

---

packages/util/src/is/bigInt.ts

Remove instanceof check
... something missed in https://github.com/polkadot-js/common/issues/1262

instanceof BigInt

---

packages/networks/src/defaults.ts

Added configuration for Sora network

Add Sora network

---

package.json
packages/hw-ledger-transports/package.json
packages/util-crypto/package.json
packages/x-randomvalues/package.json
yarn.lock

Part of https://github.com/polkadot-js/common/issues/1311

Bump noble

---

packages/util-crypto/src/blake2/asU8a.ts
packages/util-crypto/src/cryptoInit.ts
packages/util-crypto/src/hmac/shaAsU8a.ts
packages/util-crypto/src/keccak/asU8a.ts
packages/util-crypto/src/pbkdf2/encode.ts
packages/util-crypto/src/scrypt/encode.ts
packages/util-crypto/src/secp256k1/compress.ts
packages/util-crypto/src/secp256k1/expand.ts
packages/util-crypto/src/secp256k1/pair/fromSeed.ts
packages/util-crypto/src/secp256k1/recover.ts
packages/util-crypto/src/secp256k1/sign.ts
packages/util-crypto/src/sha/asU8a.ts

Closes https://github.com/polkadot-js/common/issues/1311

Upstream @noble packages

---

packages/hw-ledger-transports/src/detectOther.ts
packages/hw-ledger/src/detectOther.ts
packages/hw-ledger/src/detectPackage.ts
packages/keyring/src/detectOther.ts
packages/keyring/src/detectPackage.ts
packages/networks/src/detectOther.ts
packages/util-crypto/src/detectOther.ts
packages/util-crypto/src/detectPackage.ts
packages/util/src/detectOther.ts
packages/util/src/detectPackage.ts
packages/util/src/has.ts
packages/util/src/versionDetect.spec.ts
packages/util/src/versionDetect.ts

As per https://github.com/polkadot-js/dev/pull/550

Introduce detectOther

---

CHANGELOG.md
packages/x-randomvalues/src/browser.ts
test-bundle.html

Replacement for https://github.com/polkadot-js/common/pull/1352
(With local test-bundle.html verification)

Use x-global inside x-randomvalues

---

package.json
yarn.lock

Pulls in https://github.com/polkadot-js/dev/pull/557

Bump dev (w/ CONTRIBUTORS & umd)

---

CHANGELOG.md
package.json
packages/hw-ledger-transports/package.json
packages/x-randomvalues/package.json
yarn.lock

Pulls in https://github.com/polkadot-js/dev/pull/625

Support bundlers where import.meta.url is undefined

---

package.json
packages/hw-ledger-transports/package.json
packages/hw-ledger/package.json
packages/keyring/package.json
packages/networks/package.json
packages/util-crypto/package.json
packages/util/package.json
packages/x-bigint/package.json
packages/x-bundle/package.json
packages/x-fetch/package.json
packages/x-global/package.json
packages/x-randomvalues/package.json
packages/x-textdecoder/package.json
packages/x-textencoder/package.json
packages/x-ws/package.json
yarn.lock

Should hopefully help with https://github.com/polkadot-js/common/issues/1422

Bump dev (w/ CJS react-native key)

---

packages/networks/src/defaults/genesis.ts

Signed-off-by: lovesh <lovesh.bond@gmail.com>

Update genesis hash of Dock mainnet

---

packages/util-crypto/src/secp256k1/pair/fromSeed.ts

As per https://github.com/polkadot-js/wasm/issues/307#issuecomment-1072954942

Fail on invalid secp256k1 publicKey generation

---

packages/util-crypto/package.json

Reverses https://github.com/polkadot-js/common/pull/1444 (test)

Re-add browser entry for util-crypto

---

packages/hw-ledger/src/defaults.ts
packages/networks/src/defaults/genesis.ts
packages/networks/src/defaults/ledger.ts

We (Zondax) are developing the Statemint app (as we developed also the Statemine one) and we'll need to use it in polkadot.js.org/apps.
If there's something wrong, please tell me and I'll try to answer you as soon as possible!

feat(networks): add statemint to KnownLedger

---

packages/hw-ledger/package.json
packages/hw-ledger/src/defaults.ts
packages/networks/src/defaults/genesis.ts
packages/networks/src/defaults/ledger.ts
yarn.lock

We (at Zondax) are developing the [Parallel](https://parallel.fi) Ledger app.

add parallel to KnownLedger

---

packages/hw-ledger/src/defaults.ts
packages/networks/src/defaults/genesis.ts
packages/networks/src/defaults/ledger.ts

Hi!
I also changed the genesis hash for Centrifuge, as they migrated to a new chain.
Thanks Jaco!

add Composable support for ledger

---

packages/util/src/string/camelCase.spec.ts
packages/util/src/string/camelCase.ts
packages/util/src/string/lowerFirst.spec.ts
packages/util/src/string/lowerFirst.ts
packages/util/src/string/upperFirst.spec.ts

Small camelCase conversion adjustments

---

CHANGELOG.md
packages/util/src/bundle.ts
packages/util/src/float/index.ts
packages/util/src/float/toU8a.spec.ts
packages/util/src/float/toU8a.ts
packages/util/src/u8a/index.ts
packages/util/src/u8a/toFloat.spec.ts
packages/util/src/u8a/toFloat.ts

Base infrastructure for https://github.com/polkadot-js/api/pull/4956

floatToU8a & u8aToFloat

---

CHANGELOG.md
package.json
packages/hw-ledger-transports/package.json
packages/hw-ledger/package.json
packages/keyring/package.json
packages/networks/package.json
packages/util-crypto/package.json
packages/util/package.json
packages/util/src/hex/toU8a.spec.ts
packages/util/src/hex/toU8a.ts
packages/x-bigint/package.json
packages/x-bundle/package.json
packages/x-fetch/package.json
packages/x-global/package.json
packages/x-randomvalues/package.json
packages/x-textdecoder/package.json
packages/x-textencoder/package.json
packages/x-ws/package.json
yarn.lock

Regression from 9.4.1
Closes https://github.com/polkadot-js/api/issues/4981

Fix `hexToU8a` where `0x` is not correctly converted

---

packages/hw-ledger/src/defaults.ts
packages/networks/src/defaults/ledger.ts

@carlosala.  Hi. Sorry to bother you again, just want you to notice this.

add ledger support for stafi

---

packages/hw-ledger/package.json
packages/hw-ledger/src/defaults.ts
packages/networks/src/defaults/ledger.ts
yarn.lock

* update `@zondax/ledger-substrate`
* add hydradx to knownLedger

add hydradx to knownLedger

---

CHANGELOG.md
packages/util/src/bi/toHex.spec.ts
packages/util/src/bi/toHex.ts
packages/util/src/bi/toU8a.spec.ts
packages/util/src/bi/toU8a.ts
packages/util/src/bn/toHex.spec.ts
packages/util/src/bn/toHex.ts
packages/util/src/bn/toU8a.spec.ts
packages/util/src/bn/toU8a.ts

Closes https://github.com/polkadot-js/common/issues/1659

Ensure `{bn, n}ToHex` respects `bitLength` with 0 values

---

CHANGELOG.md
packages/util/src/number/toHex.spec.ts
packages/util/src/number/toHex.ts
packages/util/src/number/toU8a.spec.ts
packages/util/src/number/toU8a.ts

Same as in https://github.com/polkadot-js/common/pull/1660

Correct numberToHex(0) conversion

---

packages/hw-ledger/package.json
packages/hw-ledger/src/defaults.ts
packages/networks/src/defaults/genesis.ts
packages/networks/src/defaults/ledger.ts
yarn.lock

Hi Jaco!
One more Ledger app!
Thanks for your work :)

feat(networks): support ledger for origintrail

---

packages/hw-ledger/package.json
packages/hw-ledger/src/defaults.ts
packages/networks/src/defaults/genesis.ts
packages/networks/src/defaults/ledger.ts
yarn.lock

One more to the bag!
Thanks Jaco 😉

feat(networks): support ledger for ajuna 

---

CHANGELOG.md
packages/util/src/has.ts
packages/util/src/is/buffer.ts

Works around this specific comment https://github.com/polkadot-js/api/issues/5359#issuecomment-1341473473

Adjust Buffer check

---

CHANGELOG.md
package.json
packages/hw-ledger-transports/package.json
packages/hw-ledger/package.json
packages/keyring/package.json
packages/networks/package.json
packages/util-crypto/package.json
packages/util/package.json
packages/util/src/format/formatBalance.ts
packages/x-bigint/package.json
packages/x-bundle/package.json
packages/x-fetch/package.json
packages/x-global/package.json
packages/x-randomvalues/package.json
packages/x-textdecoder/package.json
packages/x-textencoder/package.json
packages/x-ws/package.json
yarn.lock

Drop stray `console.error` log

---

package.json
packages/hw-ledger/src/defaults.spec.ts
yarn.lock

This is not quite expressive - https://github.com/polkadot-js/common/actions/runs/3983758421/jobs/6829720991#step:4:825

Adjust Ledger check naming

---

packages/hw-ledger/src/defaults.ts
packages/networks/src/defaults/genesis.ts
packages/networks/src/defaults/ledger.ts

Hi Jaco!
Another Ledger app. Could you please release here and in @polkadot/apps? The team is a bit in a rush with the testing and all the stuff 😅 
Thanks!

feat(networks): support ledger for picasso

---

packages/hw-ledger/package.json
packages/hw-ledger/src/defaults.ts
packages/networks/src/defaults/genesis.ts
packages/networks/src/defaults/ledger.ts
yarn.lock

feat(networks): support ledger for pendulum

---

packages/networks/src/defaults/genesis.ts

Add https://github.com/3dpass/ network

feat: add 3dpass network

---

package.json
packages/keyring/src/keyring.ts
packages/keyring/src/pair/types.ts
packages/util-crypto/src/blake2/asU8a.ts
packages/util/src/bi/toHex.ts
packages/util/src/format/formatBalance.ts
packages/util/src/versionDetect.spec.ts
packages/util/src/versionDetect.ts
yarn.lock

Requires https://github.com/polkadot-js/dev/pull/1018

Bump dev (w/ lint updates)

---

packages/util-crypto/src/nacl/tweetnacl.ts

After https://github.com/polkadot-js/common/pull/1799

Trace tweetnacl usage (step 3: comment all code)

---

packages/util-crypto/src/nacl/tweetnacl.ts

After https://github.com/polkadot-js/common/pull/1800

Trace tweetnacl usage (step 4: apply TS types)

---

packages/util-crypto/src/nacl/tweetnacl.ts

After https://github.com/polkadot-js/common/pull/1801

Trace tweetnacl usage (Step 5: secretbox & .open available)

---

packages/hw-ledger/src/defaults.ts
packages/networks/src/defaults/genesis.ts
packages/networks/src/defaults/ledger.ts
packages/networks/src/index.spec.ts

I forgot to add this app in the past, here you have!
Thanks Jaco :)

feat(networks): add zeitgeist Ledger support

---

CHANGELOG.md
packages/util-crypto/src/base32/helpers.ts
packages/util-crypto/src/base58/validate.spec.ts
packages/util-crypto/src/base64/bs64.ts
packages/util-crypto/src/base64/validate.spec.ts

Closes https://github.com/polkadot-js/common/issues/1841

Only allow padding characters in base64 strings

---

CHANGELOG.md
packages/util/src/versionDetect.ts

Follow-up for https://github.com/polkadot-js/common/pull/1890

Fix build for esm/cjs warning additions

---

package.json
yarn.lock

Bump dev to include topo sort for releases.

Bump @polkadot/dev to 0.79.1 w/ topo sort

---

packages/hw-ledger/package.json
packages/hw-ledger/src/defaults.ts
packages/networks/src/defaults/genesis.ts
packages/networks/src/defaults/ledger.ts
yarn.lock

add ledger support for peaq
peaq is listed in - 
BIP-0044 - https://github.com/satoshilabs/slips/blob/master/slip-0044.md
ledger-substrate-js - https://github.com/Zondax/ledger-substrate-js/pull/115

Add peaq support for ledger

---

packages/hw-ledger/src/defaults.ts
packages/networks/src/defaults/genesis.ts
packages/networks/src/defaults/ledger.ts

SLIP0044 ID merged into registry: https://github.com/satoshilabs/slips/pull/1893

Add Liberland support to Generic Ledger App

---

packages/x-randomvalues/src/react-native.ts

* Remove fallback to insecure random values
* Add error messages for missing secure RNG support

fix: enhance error handling for secure random number generation in React Native
